### ISSUE TITLE
[Spec] ModInfo v2

### ISSUE THREAD

**Issue by dustinlacewell** [disunity-hq/core#15]
This issue is for tracking the design and implementation of ModInfo v2.

**Background:**

`Disunity.Core.ModInfo` is the class backing the mod-archive meta-data file-format. It must contain any information that may be needed to handle the mod in the usual contexts, whether it be the store, manager or loader. Below are a synopsis of its fields followed by a more in-depth section on each field.

## Valid patterns:
```
   SLUG_PATTERN = ^[a-z0-9]+(?:-[a-z0-9]+)*$
   NAME_PATTERN = ^[a-zA-Z0-9 -_]+$
   WORD_PATTERN = ^[a-zA-Z0-9-_]+$
  CLASS_PATTERN = ^[a-zA-Z]+$
PACKAGE_PATTERN = ^[a-z0-9]+(?:-[a-z0-9]+)*/[a-z0-9]+(?:-[a-z0-9]+)*$
VERSION_PATTERN = ^[0-9]+\\.[0-9]+\\.[0-9]+$
    DLL_PATTERN = ^[a-zA-Z0-9-_]+\\.dll$
```

## Pattern examples:
```
   SLUG_PATTERN = this-is-a-slug
   NAME_PATTERN = This is a super-great name
   WORD_PATTERN = This-is_a_Word
  CLASS_PATTERN = OnlyLettersAllowedBasically
PACKAGE_PATTERN = org-slug/mod-slug
VERSION_PATTERN = 00.123.9
    DLL_PATTERN = Some-Word_Here.dll
```

## Field summary:
- `Name` `string` : The author-unique mod name.
- `Author` `string` : The globally-unique author name.
- `Version` `string` : The mod-unique version string.
- `Description` `string` : A short description of the mod's functionality.
- `UnityVersion` `string` : The Unity version this mod was exported from.
- `Dependencies` `string[]` : A list of globally-unique mod "full names" `{author}-{name}--{version}`.
- `Artifacts` `string[]` : A list of unmanaged data-files contained within the mod.
- `PreloadAssemblies` `string[]` : A list of preloader assemblies contained within the mod.
- `RuntimeAssemblies` `string[]` : A list of runtime assemblies contained within the mod.
- `PreloadAssembly` `string` : The preload assembly from which to load the `PreloadClass`.
- `PreloadClass` `string` : The class to load from the named `PreloadAssembly`.
- `RuntimeAssembly` `string` : The runtime assembly from which to load the `RuntimeClass`.
- `RuntimeClass` `string` : The class to load from the named `RuntimeAssembly`.
- `ContentTypes` `int` : An integer flag-enum denoting the types of content in this mod.
- `IsEnabled` `bool` : Boolean denoting whether the user wants this mod loaded.

## Current schema:

```json
 {
   "$schema": "http://json-schema.org/draft-04/schema#",
   "type": "object",
   "properties": {
     "OrgID": {
       "type": "string",
       "maxLength": 128,
       "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
     },
     "ModID": {
       "type": "string",
       "maxLength": 128,
       "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
     },
     "Version": {
       "type": "string",
       "maxLength": 128,
       "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+$"
     },
     "Name": {
       "type": "string",
       "maxLength": 128,
       "pattern": "^[a-zA-Z0-9 -_]+$"
     },
     "Url": {
       "type": "string",
       "maxLength": 128,
       "format": "url"
     },
     "Description": {
       "type": "string",
       "maxLength": 128
     },
     "ContentTypes": {
       "type": "integer"
     },
     "Targets": {
       "type": "object",
       "additionalProperties": {
         "type": "object",
         "properties": {
           "MinVersion": {
             "type": "string",
             "maxLength": 128
           },
           "MaxVersion": {
             "type": "string",
             "maxLength": 128
           }
         }
       }
     },
     "Dependencies": {
       "type": "object",
       "additionalProperties": {
         "type": "object",
         "properties": {
           "MinVersion": {
             "type": "string",
             "maxLength": 128
           },
           "MaxVersion": {
             "type": "string",
             "maxLength": 128
           }
         }
       }
     },
     "Artifacts": {
       "type": "array",
       "items": {
         "type": "string",
         "maxLength": 128
       }
     },
     "PreloadAssemblies": {
       "type": "array",
       "items": {
         "type": "string",
         "maxLength": 128,
         "pattern": "^[a-zA-Z0-9-_]+\\.dll$"
       }
     },
     "PreloadAssembly": {
       "type": "string",
       "maxLength": 128,
       "pattern": "^[a-zA-Z]+$"
     },
     "PreloadClass": {
       "type": "string",
       "maxLength": 128,
       "pattern": "^[a-zA-Z]+$"
     },
     "RuntimeAssemblies": {
       "type": "array",
       "items": {
         "type": "string",
         "maxLength": 128,
         "pattern": "^[a-zA-Z0-9-_]+\\.dll$"
       }
     },
     "RuntimeAssembly": {
       "type": "string",
       "maxLength": 128,
       "pattern": "^[a-zA-Z]+$"
     },
     "RuntimeClass": {
       "type": "string",
       "maxLength": 128,
       "pattern": "^[a-zA-Z]+$"
     }
   },
   "required": [
     "OrgID",
     "ModID",
     "Name",
     "Url",
     "Version",
     "Description",
     "Targets",
     "ContentTypes"
   ]
 }
```

### Name
**Required**
**Allowed characters:** Alphanumeric, underscores
**Max length:** 32

The mod's name should be unique to the author. We can enforce this within the exporter and the store.

### Author
**Required**
**Allowed characters:** Alphanumeric, underscores

The author's name should be globally-unique to the store. We can enforce this within the exporter and the store.

### Version
**Required**
**Allowed characters:**: Alphanumeric, periods, hyphens

#### Open Questions:

- `Q`: How formalized/freeform should we be with version strings?
- `A`: 

- `Q`: Should we enforce semvar?
- `A`: 

- `Q`: Should we enforce versions always go up? (exporter/store validation)
- `A`: 

### Description
**Required**
**Allowed characters:** Any

The description will be used in many places and should be short description of the functionality of the mod.

#### Open Questions:

- `Q`: What should the max length be?
- `A`:

### UnityVersion
**Required**

Denotes the version of Unity that was running the exporter when the mod was exported. This is a hold-over from MultiMod.

- `Q`: Is this even useful?
- `A`:

### Dependencies
**Optional**
**Allowed values:** Valid globally-unique mod identifiers.

This currently uses the Thunderstore format of `{author}-{modname}--{version}`. We may want to expand this to include semver ranges and the like.

### Artifacts
**Optional**

Artifacts are files, of any sort, the mod author wanted to include in their mod archive. These files are stored within the `artifacts/` folder of the archive. The values in this list are the relative paths to those files from the `artifacts/` folder.

### PreloadAssemblies
**Optional**

Preload assemblies are stored within the `preload/` folder within the mod archive. This list contains assembly names, not file names, representing the assemblies within the archive.

Preload assemblies are loaded before the game is, and are separated so that they can avoid loading any of the dependencies a mod's runtime assemblies might have.

### RuntimeAssemblies
**Optional**

Runtime assemblies are stored within the `runtime/` folder within the mod archive. This list contains assembly names, not file names, representing the assemblies within the archive.

Runtime assemblies are loaded after the game is, and are separated so that they can utilize dependencies that any runtime assemblies would want to avoid.

### PreloadAssembly and PreloadClass
**Optional**
**Coupled**

When either is present, the other is required. These are the assembly name and class name of a class that Disunity should instantiate during the preloader phase.

- `Q`: Do we want/need/have-bandwidth to support multiple PreloadClasses for v2?
- `A`:

### RuntimeAssembly and RuntimeClass
**Optional**
**Coupled**

When either is present, the other is required. These are the assembly name and class name of a class that Disunity should instantiate during the runtime phase.

- `Q`: Do we want/need/have-bandwidth to support multiple RuntimeClasses for v2?
- `A`:

### ContentTypes
**Required**

This flag enum is serialized as an integer. It denotes which of all the possible types of content supported by Disunity, this mod contains.

### IsEnabled
**Required**

Denotes whether the user wants this mod loaded (despite it being installed). This is typically utilized by the mod-manager to store that state. This may not be the best place to put this...

- `Q`: Should we keep manager state like this somewhere else?
- `A`: 

## Tracked Issues:

- #14 Semantic Versioning

**Comment by MythicManiac** [comment]
My thoughts on the Q/A
---

Q: How formalized/freeform should we be with version strings?
A: As strict as possible, while still allowing for relevant flexibility (e.g. version range support for dependencies). A better question probably is should we support pre releases for example?

Q: Should we enforce semver?
A: Yes

Q: Should we enforce versions always go up? (exporter/store validation)
A: Probably not. There are times where you might be supporting two separate major versions at the same time.

Q: What should the description max length be?
A: Something fairly short so it can be used in small UI fields. Currently on Thunderstore it's capped at 256, but always open for change if there's a reason of course.

Q: Is unity version even useful?
A: Probably not

Q: Do we want/need/have-bandwidth to support multiple PreloadClasses for v2?
A: It might cause unneeded complexity. How about letting the PreloadClass either be a single entry, or an array?

Q: Do we want/need/have-bandwidth to support multiple RuntimeClasses for v2?
A: Same as above

Q: Should we keep manager state like `IsEnabled` somewhere else?
A: Probably

Other thoughts
---

- Probably should add a manifest version field as well, so that tools can parse it easily even if the format changes
- How about adding support for some more free form extra data? It would probably increase the lifetime of this version's spec, as the extra data fields could be abused for new features. Additionally how the extra data would end up being used would be a good way to see what to take in to v3.

**Comment by dustinlacewell** [comment]
> **Q: Do we want/need/have-bandwidth to support multiple PreloadClasses for v2?**
> A: It might cause unneeded complexity. How about letting the PreloadClass either be a single entry, or an array?

Yeah array is easy enough, the effort would come from exporter UX mostly.

> * How about adding support for some more free form extra data?

I like this idea. I think someone will have to take a look at a more robust serialization solution for core than what we're using right now though.
